"""initial_schema

Revision ID: 2f00228655b3
Revises: 
Create Date: 2026-09-26 12:51:36.505082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f00228655b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('emit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedupe_key', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_enabled'), 'alert_rules', ['enabled'], unique=False)
    op.create_table('batteries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('battery_id', sa.String(length=64), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batteries_battery_id'), 'batteries', ['battery_id'], unique=True)
    op.create_table('technicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battery_metric_snapshots',
    sa.Column('battery_pk', sa.UUID(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('inverter_status', sa.String(length=32), nullable=True),
    sa.Column('grid_status', sa.String(length=32), nullable=True),
    sa.Column('backup_available', sa.Boolean(), nullable=True),
    sa.Column('connectivity', sa.String(length=32), nullable=True),
    sa.Column('fault_code', sa.String(length=64), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['battery_pk'], ['batteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('battery_pk')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=32), nullable=False),
    sa.Column('battery_pk', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='incident_status'), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('fault_code', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('priority_rationale', sa.String(length=1024), nullable=True),
    sa.Column('rca', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_technician_id', sa.UUID(), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['battery_pk'], ['batteries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_alert_type'), 'incidents', ['alert_type'], unique=False)
    op.create_index(op.f('ix_incidents_battery_pk'), 'incidents', ['battery_pk'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_ticket_id'), 'incidents', ['ticket_id'], unique=True)
    op.create_table('service_records',
    sa.Column('battery_pk', sa.UUID(), nullable=False),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['battery_pk'], ['batteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('battery_pk')
    )
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('battery_pk', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Enum('metric', 'log', 'device_incident', name='telemetry_event_kind'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['battery_pk'], ['batteries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_battery_pk'), 'telemetry_events', ['battery_pk'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event_id'), 'telemetry_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_telemetry_events_event_time'), 'telemetry_events', ['event_time'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_pk', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Enum('rule', 'human', name='incident_event_source'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_pk'), 'incident_events', ['incident_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_events_incident_pk'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_telemetry_events_event_time'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_battery_pk'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_table('service_records')
    op.drop_index(op.f('ix_incidents_ticket_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_battery_pk'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_alert_type'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('battery_metric_snapshots')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_batteries_battery_id'), table_name='batteries')
    op.drop_table('batteries')
    op.drop_index(op.f('ix_alert_rules_enabled'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
