"""dtc_catalog

Revision ID: edd0d13b9436
Revises: 2f00228655b3
Create Date: 2026-09-26 15:22:46.774124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edd0d13b9436'
down_revision: Union[str, Sequence[str], None] = '2f00228655b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtc_catalog_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('severity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dtc_entries',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('category_code', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('detect', sa.Text(), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('dispatch', sa.String(length=32), nullable=False),
    sa.Column('recovery', sa.String(length=32), nullable=False),
    sa.Column('inject', sa.Text(), nullable=True),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_dtc_entries_category_code'), 'dtc_entries', ['category_code'], unique=False)
    op.create_index(op.f('ix_dtc_entries_demo'), 'dtc_entries', ['demo'], unique=False)
    op.create_index(op.f('ix_dtc_entries_severity'), 'dtc_entries', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dtc_entries_severity'), table_name='dtc_entries')
    op.drop_index(op.f('ix_dtc_entries_demo'), table_name='dtc_entries')
    op.drop_index(op.f('ix_dtc_entries_category_code'), table_name='dtc_entries')
    op.drop_table('dtc_entries')
    op.drop_table('dtc_catalog_meta')
    # ### end Alembic commands ###
