# ruff: noqa: E501 — catalog strings are intentionally long

DTCS: list[dict] = [
    {
        "code": "BAT-001",
        "cat": "BAT",
        "title": "Cell overvoltage (L1)",
        "detect": "Any cell > 3.65 V for 1 s",
        "reaction": "Stop charging; allow discharge",
        "sev": 3,
        "dispatch": "derated",
        "recovery": "auto",
        "inject": "cell_v[i] = 3.70",
        "demo": False,
    },
    {
        "code": "BAT-002",
        "cat": "BAT",
        "title": "Cell overvoltage (L2)",
        "detect": "Any cell > 3.80 V for 200 ms",
        "reaction": "Open contactors, latch fault",
        "sev": 4,
        "dispatch": "out",
        "recovery": "truck",
        "inject": "cell_v[i] = 3.85",
        "demo": False,
    },
    {
        "code": "BAT-003",
        "cat": "BAT",
        "title": "Cell undervoltage (L1)",
        "detect": "Any cell < 2.80 V for 1 s",
        "reaction": "Stop discharging; charge allowed",
        "sev": 3,
        "dispatch": "derated",
        "recovery": "auto",
        "inject": "cell_v[i] = 2.70",
        "demo": False,
    },
    {
        "code": "BAT-004",
        "cat": "BAT",
        "title": "Cell deep undervoltage",
        "detect": "Any cell < 2.00 V",
        "reaction": "Latch; block charging (copper dissolution risk)",
        "sev": 4,
        "dispatch": "out",
        "recovery": "truck",
        "inject": "cell_v[i] = 1.90",
        "demo": False,
    },
    {
        "code": "BAT-005",
        "cat": "BAT",
        "title": "Cell imbalance",
        "detect": "Max-min cell ΔV > 50 mV at rest",
        "reaction": "Run balancing; log",
        "sev": 1,
        "dispatch": "full",
        "recovery": "auto",
        "inject": "cell_v[i] -= 0.06",
        "demo": False,
    },
    {
        "code": "BAT-006",
        "cat": "BAT",
        "title": "Persistent imbalance",
        "detect": "ΔV > 150 mV after 24 h balancing",
        "reaction": "Shrink usable SOC window",
        "sev": 2,
        "dispatch": "derated",
        "recovery": "remote",
        "inject": "cell_v[i] -= 0.16; balancing=off",
        "demo": False,
    },
    {
        "code": "BAT-007",
        "cat": "BAT",
        "title": "Charge overcurrent",
        "detect": "Pack current > charge limit + 10% for 500 ms",
        "reaction": "Inverter clamps current, then opens contactors",
        "sev": 3,
        "dispatch": "derated",
        "recovery": "retry",
        "inject": "i_pack = 1.3*CCL",
        "demo": False,
    },
    {
        "code": "BAT-008",
        "cat": "BAT",
        "title": "Discharge short circuit",
        "detect": "Pack current > 5x rated or fuse sense open",
        "reaction": "Fuse/pyro clears; latch",
        "sev": 4,
        "dispatch": "out",
        "recovery": "truck",
        "inject": "i_pack = 6*rated",
        "demo": False,
    },
    {
        "code": "BAT-009",
        "cat": "BAT",
        "title": "SOC estimate divergence",
        "detect": "Coulomb count vs OCV model differ > 8% (flat LFP curve)",
        "reaction": "Raise backup reserve; schedule full-charge recalibration",
        "sev": 1,
        "dispatch": "derated",
        "recovery": "auto",
        "inject": "soc_bias += 0.12",
        "demo": True,
    },
    {
        "code": "BAT-010",
        "cat": "BAT",
        "title": "SOH below threshold",
        "detect": "Estimated capacity < 80% of nameplate",
        "reaction": "Flag for replacement planning; resize dispatch",
        "sev": 1,
        "dispatch": "derated",
        "recovery": "remote",
        "inject": "capacity_kwh *= 0.78",
        "demo": False,
    },
    {
        "code": "BAT-011",
        "cat": "BAT",
        "title": "High internal resistance",
        "detect": "Module DCIR > 1.5x fleet baseline",
        "reaction": "Derate current",
        "sev": 2,
        "dispatch": "derated",
        "recovery": "remote",
        "inject": "r_int[m] *= 1.6",
        "demo": False,
    },
    {
        "code": "BAT-012",
        "cat": "BAT",
        "title": "Abnormal self-discharge",
        "detect": "Cell drops > 10 mV/day faster than peers at rest",
        "reaction": "Suspected internal short; stop and flag",
        "sev": 3,
        "dispatch": "out",
        "recovery": "truck",
        "inject": "cell_leak[i] = 0.02",
        "demo": False,
    },
    {
        "code": "BAT-013",
        "cat": "BAT",
        "title": "Module count mismatch",
        "detect": "Detected modules ≠ configured",
        "reaction": "Refuse to start",
        "sev": 4,
        "dispatch": "out",
        "recovery": "truck",
        "inject": "modules_detected -= 1",
        "demo": False,
    },
    {
        "code": "BAT-014",
        "cat": "BAT",
        "title": "Pack voltage plausibility",
        "detect": "Pack V vs Σ cell V differ > 1%",
        "reaction": "Suspect sensing; derate",
        "sev": 2,
        "dispatch": "derated",
        "recovery": "auto",
        "inject": "v_pack_bias = 0.02",
        "demo": False,
    },
    {
        "code": "BAT-015",
        "cat": "BAT",
        "title": "Backup reserve breach",
        "detect": "SOC < member backup reserve while grid-connected",
        "reaction": "Cancel discharge dispatch; recharge",
        "sev": 1,
        "dispatch": "derated",
        "recovery": "auto",
        "inject": "soc = reserve - 0.05",
        "demo": True,
    },
]

from app.features.dtc.bundled.entries_bms import ENTRIES as _BMS  # noqa: E402
from app.features.dtc.bundled.entries_thm import ENTRIES as _THM  # noqa: E402
from app.features.dtc.bundled.entries_inv import ENTRIES as _INV  # noqa: E402
from app.features.dtc.bundled.entries_grd import ENTRIES as _GRD  # noqa: E402
from app.features.dtc.bundled.entries_hub import ENTRIES as _HUB  # noqa: E402
from app.features.dtc.bundled.entries_der import ENTRIES as _DER  # noqa: E402
from app.features.dtc.bundled.entries_com import ENTRIES as _COM  # noqa: E402
from app.features.dtc.bundled.entries_swf import ENTRIES as _SWF  # noqa: E402
from app.features.dtc.bundled.entries_flt import ENTRIES as _FLT  # noqa: E402
from app.features.dtc.bundled.entries_ins import ENTRIES as _INS  # noqa: E402

DTCS = DTCS + _BMS + _THM + _INV + _GRD + _HUB + _DER + _COM + _SWF + _FLT + _INS
