# ruff: noqa: E501

ENTRIES: list[dict] = [
    {"code": "INV-001", "cat": "INV", "title": "DC-link overvoltage", "detect": "V_dc > max for 1 ms", "reaction": "Gate off; auto-restart", "sev": 3, "dispatch": "out", "recovery": "retry", "inject": "v_dc = 1.2*max", "demo": False},
    {"code": "INV-002", "cat": "INV", "title": "DC-link undervoltage", "detect": "V_dc < min", "reaction": "Gate off", "sev": 3, "dispatch": "out", "recovery": "retry", "inject": "v_dc = 0.7*min", "demo": False},
    {"code": "INV-003", "cat": "INV", "title": "Output overcurrent", "detect": "Instantaneous current > trip", "reaction": "Gate off; 3 retries then latch", "sev": 3, "dispatch": "out", "recovery": "retry", "inject": "i_out = 2.5*rated", "demo": False},
    {"code": "INV-004", "cat": "INV", "title": "Gate driver / desaturation", "detect": "Driver desat flag", "reaction": "Gate off; latch after repeats", "sev": 4, "dispatch": "out", "recovery": "truck", "inject": "desat = True", "demo": False},
    {"code": "INV-005", "cat": "INV", "title": "Branch short in backup mode", "detect": "Output current limit reached with V collapse while islanded", "reaction": "Supply fault current long enough to trip house breaker, then stop", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "house_short = True", "demo": False},
    {"code": "INV-006", "cat": "INV", "title": "Battery DC/DC stage fault", "detect": "DC/DC current/voltage loop error", "reaction": "Stop", "sev": 3, "dispatch": "out", "recovery": "retry", "inject": "dcdc = fault", "demo": False},
    {"code": "INV-007", "cat": "INV", "title": "Ground fault (GFDI)", "detect": "Residual current > 30 mA", "reaction": "Stop; latch", "sev": 4, "dispatch": "out", "recovery": "truck", "inject": "i_residual = 0.05", "demo": False},
    {"code": "INV-008", "cat": "INV", "title": "Island voltage regulation", "detect": "Island V outside ±5% for 1 s", "reaction": "Derate, then stop", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "load_step = +8kW", "demo": False},
    {"code": "INV-009", "cat": "INV", "title": "Island frequency error", "detect": "Island f outside 59.5–60.5 Hz (excluding intentional shift)", "reaction": "Stop", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "f_island = 58.9", "demo": False},
    {"code": "INV-010", "cat": "INV", "title": "DC injection", "detect": "DC component > 0.5% rated current", "reaction": "Stop", "sev": 3, "dispatch": "out", "recovery": "retry", "inject": "dc_offset = 0.01", "demo": False},
    {"code": "INV-011", "cat": "INV", "title": "PLL loss of lock", "detect": "Grid-sync PLL error > limit", "reaction": "Cease export; resync", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "phase_jump = 25", "demo": False},
    {"code": "INV-012", "cat": "INV", "title": "Output current sensor fault", "detect": "Zero offset > 1% at gate-off", "reaction": "Stop", "sev": 3, "dispatch": "out", "recovery": "truck", "inject": "i_sense_offset = 0.03", "demo": False},
    {"code": "INV-013", "cat": "INV", "title": "DC-link capacitor aging", "detect": "DC ripple > 1.5x baseline at same power", "reaction": "Predictive maintenance flag", "sev": 1, "dispatch": "full", "recovery": "remote", "inject": "esr *= 2", "demo": False},
    {"code": "INV-014", "cat": "INV", "title": "AC output relay welded", "detect": "Voltage present across open relay", "reaction": "Latch", "sev": 4, "dispatch": "out", "recovery": "truck", "inject": "ac_relay = welded", "demo": False},
    {"code": "INV-015", "cat": "INV", "title": "High current THD", "detect": "THD > 5% at > 30% load", "reaction": "Log", "sev": 1, "dispatch": "full", "recovery": "auto", "inject": "thd = 0.07", "demo": False},
    {"code": "INV-016", "cat": "INV", "title": "Setpoint above BMS limit", "detect": "Cloud setpoint > CCL/DCL", "reaction": "Clamp to limit; report", "sev": 0, "dispatch": "derated", "recovery": "auto", "inject": "cmd_kw = 15", "demo": False},
    {"code": "INV-017", "cat": "INV", "title": "Backup overload", "detect": "Load > 11 kW (110% for 10 s, 150% for 200 ms)", "reaction": "Timed trip; shed if smart breakers present", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "house_load = 13kW", "demo": True},
    {"code": "INV-018", "cat": "INV", "title": "Motor-start surge", "detect": "AC compressor LRA > inverter surge capacity (~160 A)", "reaction": "Voltage sag; trip; retry with soft start", "sev": 3, "dispatch": "out", "recovery": "auto", "inject": "lra = 190A", "demo": False},
]
